name: Build

on:
  workflow_call:

jobs:
  build-artifact:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build binary
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifactor-linux-amd64
          path: bin/artifactor
